#!/bin/bash

export PYTHONUNBUFFERED=1
export VENV_PATH="/venv"

if [ ! -d "${VENV_PATH}" ]; then
	echo "INFO: Python Virtual environment not found, creating..."
	python -m venv "${VENV_PATH}";
	echo
fi

# Print banner
if [ -f "/opt/soramitsukhmer/deploy-shell/banner.txt" ]; then
	cat /opt/soramitsukhmer/deploy-shell/banner.txt | /usr/games/lolcat
fi

# Activate virtual environment
source "${VENV_PATH}/bin/activate"
echo -e "INFO: Python Virtual environment activated!\n"
